spring:
  application:
    name: storyteller-api
  cloud:
    config:
      discovery:
        enabled: true
    
server:
  port: 9977

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
#   registerWithEureka: false
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'