spring:
  application:
    name: storyteller-api
    
server:
  port: 7777

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'