spring:
  application:
    name: gatekeeper
  cloud:
    config:
      discovery:
        enabled: true
    
server:
  port: 9977

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
#   registerWithEureka: false

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    random-story-microservice:
      path: /stories/**
      stripPrefix: false    
  
#ribbon:
#  ReadTimeout: 10000



#hystrix:
#  command:
#    random-story-microserviceRibbonCommand:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'