server:
  port: 8888

info:
  description: Spring Cloud Config Server
  
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codependent/storyteller-microservices-config
#         uri: file:///C:/SoftDesarrollo/6-Workspaces/sts/storyteller-microservices-config
      consul:
        server:
          host: localhost
          port: 8500