server:
  port: 8888

info:
  description: Spring Cloud Config Server
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://archimedes1:8761/eureka/,http://archimedes2:8762/eureka/
    healthcheck:
      enabled: true
    
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codependent/storyteller-microservices-config
#         uri: file:///C:/SoftDesarrollo/6-Workspaces/sts/storyteller-microservices-config