eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
spring:
  application:
    name: random-image-microservice
    
server:
  port: 9999
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'