spring:
  application:
    name: random-image-microservice
  cloud:
    config:
      discovery:
        enabled: true
        
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'